services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # named volume for data
      - postgres_data:/var/lib/postgresql/data
      # bind mount for init script
      - ./infrastructure/docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}

  redis:
    image: redis:7-alpine
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      -- appendonly ${REDIS_APPENDONLY}
      -- maxmemory ${REDIS_MAXMEMORY}
      -- maxmemory-policy ${REDIS_MAXMEMORY_POLICY}
    healthcheck:
      test: redis-cli ping

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local


